local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{year}}/{{month}}/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Tech", "Life", "Music", "Travel", "Other"] }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: true }
      - { label: "Cover Image Credits", name: "credits", widget: "text", required: false }
      - { label: "Comments Enabled", name: "comments", widget: "boolean", default: true, required: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "experience"
    label: "Work Experience"
    folder: "content/about/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Company", name: "company", widget: "string" }
      - {
          label: "Start Date",
          name: "startDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: false,
          picker_utc: true,
        }
      - {
          label: "End Date",
          name: "endDate",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: false,
          picker_utc: true,
          required: false,
        }
      - { label: "Stack", name: "stack", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/about/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Last Update", name: "lastUpdate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Stack",
          name: "stack",
          widget: "list",
          field: { label: "Technology", name: "tech", widget: "string" },
        }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "URL", name: "url", widget: "string", required: false }

  - name: "bookmarks"
    label: "Bookmarks"
    folder: "content/bookmarks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: ["music", "book", "game", "podcast", "tvseries", "movie"],
        }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Bookmarked On", name: "bookmarkedOn", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", field: { label: "Tag", name: "tag", widget: "string" } }
