#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️  Styling, testing and building before commit...'

# Check Prettier standards
npm run format ||
(
    echo '🤮  Your styling looks disgusting. Prettier Check Failed.
              Run npm run format:fix, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run lint ||
(
    echo '🤮  Get that weak s**t out of here! ESLint Check Failed.
            Make the required changes listed above, add changes and try to commit again.'
    false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌  Failed Type check. Are you seriously trying to write that?
            Make the changes required above.'
    false;
)

# If everything passes... Now we can push
echo '✅  Everything is right... pushing'
